# Generated by Django 4.2.4 on 2023-08-18 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="cat",
            new_name="finch",
        ),
    ]
